

trigger:
- master

pool:
 name: Default

steps:
- script: echo "Hello World" > output.txt
  displayName: 'Run a one-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/output.txt'
    artifact: 'helloWorldOutput'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $pat = "44ewxwg6s3jt7kydmxcpxdlnte7iwbghrsebo7kdupu6uiphsbxa"
      $organization = "surveharshadv"
      $organizationUrl = "https://dev.azure.com/surveharshadv"
      $projectId = "Harsh"
      $buildId = "$(Build.BuildId)"
      $definitionId = "7"
      $apiVersion = "6.0"
      # apiVersion = "6.0-preview.2"  # Or any appropriate API version

      $url = "$organizationUrl/$projectId/_apis/build/builds?definitions=$definitionId&api-version=$apiVersion"
      
      #$url = "https://dev.azure.com/surveharshadv/Harsh/_build?definitionId=7/logs?api-version=$apiVersion"
      
      $headers = @{
          Authorization = "Bearer $pat"
      }
      
      $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
      
      # Output the build logs content
      if ($response.value.content -ne $null) {
          Write-Host "Build Logs:"
          Write-Host $response.value.content
      } else {
          Write-Host "Build logs not found or inaccessible."
      }
