

trigger:
- master

pool:
 name: Default

steps:
- script: echo "Hello World" > output.txt
  displayName: 'Run a one-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/output.txt'
    artifact: 'helloWorldOutput'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $pat = "44ewxwg6s3jt7kydmxcpxdlnte7iwbghrsebo7kdupu6uiphsbxa"
      $organization = "surveharshadv"
      $organizationUrl = "https://dev.azure.com/surveharshadv"
      $definitionId = "4"
      $projectId = "Harsh"
      $buildId = "$(Build.BuildId)"
      $apiVersion = "6.0-preview.2"

      
      $url = "$organizationUrl/$projectId/_apis/build/builds?definitions=$definitionId&api-version=$apiVersion"
      
      $headers = @{
          Authorization = "Bearer $pat"
      }
      
      $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
      
      # Output the build logs content
      if ($response.value.count -gt 0) {
       $buildId = $response.value[0].id
       $logsUrl = "https://dev.azure.com/surveharshadv/Harsh/_build?definitionId=4/logs?api-version=$apiVersion"
       $logsResponse = Invoke-RestMethod -Uri $logsUrl -Headers $headers -Method Get
       if ($logsResponse.value.content -ne $null) {
          Write-Host "Build logs content:"
          Write-Host $logsResponse.value.content
      }
       else {
          Write-Host "Build logs not found or inaccessible."
      }
      }
       else {
        Write-Host "No builds found for the specified definition."
      }